addview and message
tommy1013/chat-space pull request #8
Opened 2017-08-18 08:52 UTC by tommy1013

# what
dbからデータを表示

# why
必要なため

[![https://gyazo.com/2d4e822481f103687765899e0de4acaf](https://i.gyazo.com/2d4e822481f103687765899e0de4acaf.png)](https://gyazo.com/2d4e822481f103687765899e0de4acaf)

2017-08-18 09:03 UTC, miyagit commented on app/views/messages/index.html.haml
> +  = render 'shared/side', collection: @groups
collection使わずに実装しましょう。

2017-08-18 09:03 UTC, miyagit commented on app/controllers/messages_controller.rb
> +    @groups = Group.all
allは使用しないでください。
userが所属している全グループを出す様にしてください。

2017-08-18 09:03 UTC, miyagit commented on app/controllers/messages_controller.rb
> +     @messages = Message.all
そのgroupに紐づいているメッセージを出す様にしてください。

2017-08-18 11:33 UTC, oyaoyaoyana reviewed
お待たせ致しました！
あと２点お願いします

2017-08-18 11:33 UTC, oyaoyaoya commented on app/views/shared/_side-bottom__box.haml
> +    .re_message message.boby
メッセージが無かった場合はどうなりそうでしょうか？

2017-08-18 11:33 UTC, oyaoyaoya commented on app/controllers/messages_controller.rb
> +     @messages = current_user.messages
current_userに紐づくメッセージで充分でしょうか？
もう一度考えてみましょう！

2017-08-19 06:34 UTC, toshikiohtaka commented on app/views/messages/index.html.haml
> +            %span.user_name ryosukemaehira
ここもログインしているuserの名前にしてあげましょう。

2017-08-19 08:40 UTC, offich requested changes
コメントいたしました！
お時間よろしいときに、修正お願いいたします！

2017-08-19 08:40 UTC, r-ume commented on Gemfile
> +gem 'active_decorator'
**GOOD**
`active_decorator` のこと、ご存知なんですね！大変良いです！

2017-08-19 08:40 UTC, r-ume commented on app/models/group.rb
> +  def show_last_messages
このようなメソッドは、 `group_decorator` に定義しましょう。

2017-08-19 08:40 UTC, r-ume commented on app/views/shared/_side-bottom__box.haml
> +      =group.show_last_messages
**GOOD**
部分テンプレートを使われているのは、良いです！

2017-08-19 08:40 UTC, r-ume commented on app/views/messages/index.html.haml
> +          = @group.users.pluck(:name).join(",")
このようなロジックは、`group_decorator` に定義しましょう。

2017-08-19 08:40 UTC, r-ume commented on app/views/shared/_side-bottom__box.haml
> +  - @groups.each do |group|
こちらは、`groups` と書きましょう。

2017-08-19 08:40 UTC, r-ume commented on app/views/messages/index.html.haml
> +            %span.user_name @groups.name
**THINK**
`groups` という複数形から、nameを取るというのは、コードを一目見て、エラーになるコードです。(配列の要素をしてせずに、いきなりキーにアクセスしようとするからです。）
そのため、上のように書きたいのであれば、もう一つ、`@group` という変数を定義しましょう。

2017-08-19 08:46 UTC, tommy1013 commented on app/models/group.rb
> +  def show_last_messages
短くモデルにかけているので十分だと思いますし、他のメンターにこのように指摘されて書きました。なぜgroup_decoratorに定義しなくてはいけないのでしょうか。この書き方にするのに時間をかけ、また違う書き方で書き直す意味が分かりません。

2017-08-19 08:49 UTC, r-ume commented on app/models/group.rb
> +  def show_last_messages
> 他のメンターにこのように指摘されて書きました。

こちらを存じ上げておりませんでした。失礼しました。このままで大丈夫です。

> なぜgroup_decoratorに定義しなくてはいけないのでしょうか。

モデルに、`show_last_messages` のようなメソッドを書くのは、推奨されていないからです。

2017-08-19 09:36 UTC, offich requested changes
修正お願いいたします！

2017-08-19 09:36 UTC, r-ume commented on test/decorators/group_decorator_test.rb
> +require 'test_helper'
`git rm --cached group_decorator_test.rb` でこのプルリクエストからの外していただけると幸いです。

2017-08-19 09:36 UTC, r-ume commented on app/views/shared/_side-bottom__box.haml
> +    = group.show_last_messages
**GOOD**
すっきりしましたね！decorator活用していきましょう！

2017-08-19 09:36 UTC, r-ume commented on app/views/messages/index.html.haml
> +            %span.user_name @groups.name
`@group` でお願いいたします。

2017-08-19 10:09 UTC, toshikiohtaka commented on app/views/messages/index.html.haml
> +      - @messages.each do |message|
viewファイルにeachがあると見づらくなるので、このeachブロックは部分テンプレート化しましょう。

2017-08-19 11:01 UTC, yamamotokeishiro commented on Gemfile.lock
> +    active_decorator (1.0.0)
aa

2017-08-19 11:03 UTC, yamamotokeishiro commented on app/views/shared/_side.html.haml
> +    = @user.name
これでメッセージごとのuser名前は取得できていますか？

2017-08-19 11:06 UTC, yamamotokeishiro commented on app/views/shared/_main-messages.html.haml
> +      = @user.name
これでメッセージごとのuesr名前は表示されていますでしょうか？

2017-08-21 09:27 UTC, merged